export const env = {
  DATABASE_URL: process.env.DATABASE_URL,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  NEXT_PUBLIC_STREAM_CHAT_API_KEY: process.env.NEXT_PUBLIC_STREAM_CHAT_API_KEY,
  STREAM_CHAT_SECRET_KEY: process.env.STREAM_CHAT_SECRET_KEY,
  NEXT_PUBLIC_STREAM_VIDEO_API_KEY: process.env.NEXT_PUBLIC_STREAM_VIDEO_API_KEY,
  NEXT_PUBLIC_STREAM_VIDEO_SECRET_KEY: process.env.NEXT_PUBLIC_STREAM_VIDEO_SECRET_KEY,
  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN,
};
